$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: train
display_name: Evaluation
description: Evaluate the image classifier model

inputs:
  data_input:
    type: uri_folder
    mode: ro_mount
  checkpoint_input:
    type: uri_folder
    mode: ro_mount
  batch_size:
    type: integer
  num_workers:
    type: integer
  prefetch_factor:
    type: integer
  dev_mode:
    type: boolean

environment: azureml:train-env@latest

code: ../../../../../
command: >-
  pip install . &&
  python src/image_classifier/modeling/evaluate.py
  --data_dir ${{inputs.data_input}}
  --checkpoint_dir ${{inputs.checkpoint_input}}
  --batch_size ${{inputs.batch_size}}
  --num_workers ${{inputs.num_workers}}
  --prefetch_factor ${{inputs.prefetch_factor}}
  --dev_mode ${{inputs.dev_mode}}
