$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: prepare_data
display_name: Prepare Data
description: Prepare data for training


outputs:
  data_output:
    type: uri_folder

environment: azureml:train-env@latest

code: ../../../../../
command: >-
  pip install . &&
  python src/image_classifier/data/prepare_data.py --data_dir ${{outputs.data_output}}
