repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: pretty-format-json
      args: [--indent=4, --no-sort-keys, --autofix]
    - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.13.2
  #   hooks:
  #   - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    - id: mypy
      verbose: true
      args: [
        --install-types,
        --non-interactive,
        --ignore-missing-imports,
        --disallow-untyped-defs
      ]
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
    - id: vulture
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    - id: shellcheck
      args: [
        --exclude=SC1091,
        --external-sources  
      ]
