name: pre-commit

on: [pull_request, push]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - run: |
        source requirements-cq.sh
    - uses: pre-commit/action@v3.0.1
