name: Code Quality checks with pre-commit

on: [push]

jobs:
  pre-commit:
    name: Code Quality checks with pre-commit
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Installing Poetry
      run: |
        source scripts/install-requirements-build.sh
    - name: Setting up Python virtualenv
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
        cache: "poetry"
    - name: Installing code quality requirements
      run: |
        source scripts/install-requirements-cq.sh
    - name: Running Code Quality checks with pre-commit
      uses: pre-commit/action@v3.0.1
