name: Code Quality checks with pre-commit

on: [push]

jobs:
  pre-commit:
    name: Code Quality checks with pre-commit
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository with GIT LFS
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Setting up Python3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Installing code quality requirements
      run: |
        export POETRY_VIRTUALENVS_CREATE=false
        source scripts/install-requirements-cq.sh
    - name: Running Code Quality checks with pre-commit
      uses: pre-commit/action@v3.0.1
